# Macro file for the initialization of example B2
# in interactive session
#
# Set some default verbose
#/control/verbose 2
#/control/saveHistory
/tracking/verbose 1
#/run/verbose 2

/detector/select LscDetector
/detGeometry/select lscyemilab

/event/output_file vis_output

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
